{
 "title": "Power Usage",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(changes(power{job=\"xcel-mqtt\"}[5m]) > 0)[1d:1m])",
     "legendFormat": "last update"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance, name) (count_over_time(container_last_seen{name=\"xcel-itron2mqtt\", container_label_restartcount!=\"\"}[15m])) - 1",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Instantaneous Power Consumption/Production",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "-power{job=\"xcel-mqtt\"}",
     "legendFormat": "Power"
    },
    {
     "expr": "power{job=\"solaredge\"} offset -9m",
     "legendFormat": "SolarEdge"
    }
   ]
  },
  {
   "title": "Instantaneous Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-power{job=\"xcel-mqtt\"}",
     "legendFormat": "Meter"
    },
    {
     "expr": "power{job=\"solaredge\", type=\"solaredge\"}",
     "legendFormat": "Solar"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy{type=\"current_summation_received\"}",
     "legendFormat": "Produced"
    },
    {
     "expr": "energy{type=\"current_summation_delivered\"}",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Net Energy Production",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(energy{type=\"current_summation_received\"}) - scalar(energy{type=\"current_summation_delivered\"})",
     "legendFormat": "Net"
    }
   ]
  },
  {
   "title": "Instantaneous Power Consumption/Production Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "delta(power{job=\"xcel-mqtt\"}[1m])",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "energy{type=\"current_summation_received\"}",
     "legendFormat": "Produced"
    },
    {
     "expr": "energy{type=\"current_summation_delivered\"}",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Energy Rate (Draft)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(energy{type=\"current_summation_received\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "-rate(energy{type=\"current_summation_delivered\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "tou tier",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "tou_tier", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Net Energy Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "scalar(energy{type=\"current_summation_received\"}) - scalar(energy{type=\"current_summation_delivered\"})",
     "legendFormat": "Net"
    }
   ]
  },
  { "title": "Solar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Solar Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "energy{job=\"solaredge\", type=\"lastDay\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy{job=\"solaredge\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}